Express/Controllers/BranchMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Express.Models;
using System.Net.Http;
using System.Net.Http.Json;
using Newtonsoft.Json;
using System.Text;
using System.Diagnostics;
using Express.Services;
using Express.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Express.Controllers
{
    public class BranchMVCController : Controller
    {
        private readonly IBranchService _branchService;

        public BranchMVCController(IBranchService branchService)
        {
            _branchService = branchService;
        }

        // GET: Branches
        public async Task<IActionResult> Index()
        {
            return View(await _branchService.GetAllBranches());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _branchService.GetBranch(Convert.ToInt32(id));
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Country,Address")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                var branchId = await _branchService.CreateBranch(branch);
                if (branchId > 0)
                {
                    TempData["CreateSuccess"] = $"{branch.Name} was successfully added.";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Failed to create branch, please try again.");
                }
            }
            return View(branch);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _branchService.GetBranch(Convert.ToInt32(id));
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Country,Address")] Branch branch)
        {
            if (id != branch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var updated = await _branchService.UpdateBranch(branch);
                    if (updated)
                    {
                        TempData["UpdateSuccess"] = $"Branch was successfully updated.";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Failed to update branch, please try again.");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Failed to update branch, please try again.");
                    throw;
                }
            }

            return View(branch);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _branchService.GetBranch(Convert.ToInt32(id));
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var deleted = await _branchService.DeleteBranch(id);
            if (deleted)
            {
                TempData["DeleteSuccess"] = $"Branch was successfully deleted.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Failed to delete branch, please try again.");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Express/Controllers/VehicleMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Express.Models;
using Express.Interfaces;

namespace Express.Controllers
{
    public class VehicleMVCController : Controller
    {
        private readonly IBranchService _branchService;
        private readonly IVehicleService _vehicleService;

        public VehicleMVCController(IVehicleService vehicleService, IBranchService branchService)
        {
            _vehicleService = vehicleService;
            _branchService = branchService;

        }
        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            return View(await _vehicleService.GetAllVehicles());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _vehicleService.GetVehicle(Convert.ToInt32(id));
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public async Task<IActionResult> CreateAsync()
        {
            ViewData["BranchId"] = new SelectList(await _branchService.GetAllBranches(), "Id", "Name");
            return View();
        }

        // POST: Vehicles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BranchId,Make,Model,Year,Color,Registration,Vinumber")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                var registrationExists = await _vehicleService.CheckIfRegistrationExists(vehicle.Registration);
            
                var VinNumberExists = await _vehicleService.CheckIfVinExists(vehicle.Vinumber);
                if (!VinNumberExists && !registrationExists)
                {
                    var Id = await _vehicleService.CreateVehicle(vehicle);
                    if (Id > 0)
                    {
                        TempData["CreateSuccess"] = $"Vehicle was successfully added.";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Failed to create vehicle, please try again.");
                    }
                }
                else if (VinNumberExists)
                {
                    ModelState.AddModelError("", "Vehicle vin number already exists, please check vin and try again.");
                }
                else if (registrationExists)
                {
                    ModelState.AddModelError("", "Vehicle registration already exists, please check registration and try again.");
                }
            }
            ViewData["BranchId"] = new SelectList(await _branchService.GetAllBranches(), "Id", "Name", vehicle.BranchId);
            return View(vehicle);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _vehicleService.GetVehicle(Convert.ToInt32(id));
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["BranchId"] = new SelectList(await _branchService.GetAllBranches(), "Id", "Name", vehicle.BranchId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BranchId,Make,Model,Year,Color,Registration,Vinumber,ModifiedDate")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var updated = await _vehicleService.UpdateVehicle(vehicle);
                    if (updated)
                    {
                        TempData["UpdateSuccess"] = $"Vehicle was successfully updated.";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Failed to update vehicle, please try again.");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Failed to update vehicle, please try again.");
                    throw;

                }
            }
            ViewData["BranchId"] = new SelectList(await _branchService.GetAllBranches(), "Id", "Name", vehicle.BranchId);
            return View(vehicle);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _vehicleService.GetVehicle(Convert.ToInt32(id));

            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var deleted = await _vehicleService.DeleteVehicle(id);
            if (deleted)
            {
                TempData["DeleteSuccess"] = $"Vehicle was successfully deleted.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Failed to delete vehicle, please try again.");
            }
            return RedirectToAction(nameof(Index));

        }
    }
}

Express/Controllers/WayBillMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Express.Models;
using Express.Interfaces;
using System.Text;
using Express.BusinessLayer;
using Express.Helpers;

namespace Express.Controllers
{
    public class WayBillMVCController : Controller
    {
        private readonly IWayBillService _waybillService;
        private readonly IVehicleService _vehicleService;
        private readonly IUserService _usersercice;
        BusinessLayer.Cryptography _cryptography = new BusinessLayer.Cryptography();

        public WayBillMVCController(IWayBillService waybillService, IVehicleService vehicleService, IUserService userservice)
        {
            _waybillService = waybillService;
            _vehicleService = vehicleService;
            _usersercice = userservice;
        }
        // GET: WayBills
        public async Task<IActionResult> Index()
        {
            return View(await _waybillService.GetAllWayBills());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wayBill = await _waybillService.GetWayBill(Convert.ToInt32(id));
            if (wayBill == null)
            {
                return NotFound();
            }

            return View(wayBill);
        }

        // GET: WayBills/Create
        public async Task<IActionResult> CreateAsync()
        {
            ViewData["AssignedToVehicleId"] = ViewData["AssignedToVehicleId"] = await GetVehicleListWithSelectedItem(0);
            return View();
        }

        // POST: WayBills/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AssignedToVehicleId,TotalWeight,ParcelCount,Reference,ContentDescription,VehicleStartsFrom,Destination,CreatedById,CreatedDate,Date")] WayBill wayBill)
        {
            if (ModelState.IsValid)
            {
                MethodLibrary methodLibrary = new MethodLibrary();
                var reference = methodLibrary.RandomReferenceGenerator();
                wayBill.Reference = reference;

                var encryptedEmail = SessionHelper.DoesUserEmailExist(HttpContext.Session, "EncryptedEmail");
                if (!string.IsNullOrWhiteSpace(encryptedEmail))
                {
                    var user = await _usersercice.GetUserByEmail(_cryptography.Decrypt(encryptedEmail));
                    if (user != null && user.Id > 0)
                    {
                        wayBill.CreatedById = user.Id;
                    }
                }
        

                var Id = await _waybillService.CreateWayBill(wayBill);
                if (Id > 0)
                {
                    TempData["CreateSuccess"] = $"Waybill reference is: {wayBill.Reference}";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Failed to create waybill, please try again.");
                }
            }

            ViewData["AssignedToVehicleId"] = await GetVehicleListWithSelectedItem(Convert.ToInt32(wayBill.AssignedToVehicleId));
            return View(wayBill);
        }

        public async Task<IActionResult> Assign(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wayBill = await _waybillService.GetWayBill(Convert.ToInt32(id));
            if (wayBill == null)
            {
                return NotFound();
            }

            ViewData["AssignedToVehicleId"] = ViewData["AssignedToVehicleId"] = await GetVehicleListWithSelectedItem(Convert.ToInt32(wayBill.AssignedToVehicleId));
            return View(wayBill);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var waybill = await _waybillService.GetWayBill(Convert.ToInt32(id));
            if (waybill == null)
            {
                return NotFound();
            }
            ViewData["AssignedToVehicleId"] = await GetVehicleListWithSelectedItem(Convert.ToInt32(waybill.AssignedToVehicleId));
            return View(waybill);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AssignedToVehicleId")] WayBill wayBill)
        {
            if (id != wayBill.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Destination");
            ModelState.Remove("ContentDescription");
            ModelState.Remove("VehicleStartsFrom");

            if (ModelState.IsValid)
            {
                try
                {
                    var updated = await _waybillService.UpdateWayBill(wayBill);
                    if (updated)
                    {
                        TempData["UpdateSuccess"] = $"Waybill was successfully updated.";
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("", "Failed to update waybill, please try again.");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    ModelState.AddModelError("", "Failed to update waybill, please try again.");
                }
            }
            ViewData["AssignedToVehicleId"] = await GetVehicleListWithSelectedItem(Convert.ToInt32(wayBill.AssignedToVehicleId));
            return View(wayBill);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wayBill = await _waybillService.GetWayBill(Convert.ToInt32(id));

            if (wayBill == null)
            {
                return NotFound();
            }

            return View(wayBill);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var deleted = await _vehicleService.DeleteVehicle(id);
            if (deleted)
            {
                TempData["DeleteSuccess"] = $"Waybill was successfully deleted.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("", "Failed to delete waybill, please try again.");
            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IEnumerable<SelectListItem>> GetVehicleListWithSelectedItem(int assignedToId)
        {
            List<SelectListItem> items = new SelectList(await _vehicleService.GetAllVehicles(), "Id", "VehicleDescription", assignedToId).ToList();
            var blankvehicle = new SelectListItem() { Value = "0", Text = "--- Select Vehicle ---" };
            items.Insert(0, blankvehicle);
            return items;
        }
    }
}

Express/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Express.Helpers
@{
    var email = Context.Session.GetString("EncryptedEmail");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Express</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    @*<link rel="stylesheet" href="~/lib/datatables.net-bs/css/dataTables.bootstrap.min.css" />*@
    @*<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" />*@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.9/css/fixedHeader.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/1.3.0/css/searchPanes.bootstrap4.min.css" />


    <link rel="stylesheet" href="~/lib/toastr/build/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style type="text/css">
        .help-block ul {
            list-style-type: none;
            padding: 0;
        }

        .required:after {
            content: " *";
            font-weight: normal;
            color: red;
        }
    </style>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Express</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="float:left">
                        @if (email != null && !string.IsNullOrWhiteSpace(email))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BranchMVC" asp-action="Index">Branches</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMVC" asp-action="Index">Vehicles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WayBillMVC" asp-action="Index">Waybills</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="~/Swagger/index.html">Web API</a>
                            </li>
                        }
                    </ul>

                    <ul class="nav navbar-nav" style="float:right">
                        @if (email == null || string.IsNullOrWhiteSpace(email))
                        {
                            <li><a asp-area="" asp-controller="User" asp-action="Login">Login</a></li>
                        }
                        else if (email != null && !string.IsNullOrWhiteSpace(email))
                        {

                            <li><a asp-area="" asp-controller="User" asp-action="LogOff">Logout</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Express - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/lib/sweetalert2/sweetalert2.all.min.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/fixedheader/3.1.9/js/dataTables.fixedHeader.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/searchpanes/1.3.0/js/dataTables.searchPanes.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/searchpanes/1.3.0/js/searchPanes.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/toastr/build/toastr.min.js" asp-append-version="true"></script>
    <script>
        $("a.vieweye").addClass("fa fa-eye");
        $("a.editpencil").addClass("fa fa-pencil");
        $(function () {
            var fnTimeOut = function () {
                jQuery.timeoutDialog.setupDialogTimer({
                    timeout: 1100, //in seconds-countdown(20 min)
                    countdown: 100,
                    logout_redirect_url: '@Url.Action("LogOff", "User")',
                    keep_alive_url: '@Url.Action("Keepalive", "User")'
                });
            };
            fnTimeOut();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>